use crate::config::{Config, UserConfig};
use crate::doctor::{DoctorReport, DoctorRequest};
use crate::engine::check_configured_engines;
use crate::install::{
    EnginePreference, InstallRequest, InstallState, Installer, PathProgramResolver,
    PresenterPreference, default_install_state_path,
};
use crate::runtime::{PipelineFactory, PipelineOptions};
use crate::stream::PipelinePump;
use clap::builder::OsStringValueParser;
use clap::{Args, Parser, Subcommand};
use std::env;
use std::ffi::OsString;
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process;

/// Compatibility symbol for downstream code that referenced the former static
/// help text. The canonical help is generated by Clap from the typed model.
pub const HELP: &str = "Run `ptymark --help` for the generated command reference.\n";

#[derive(Debug, Parser)]
#[command(
    name = "ptymark",
    version,
    about = "Pre-display renderer for explicit semantic blocks in terminal streams",
    disable_help_subcommand = true,
    arg_required_else_help = true,
    after_help = "Common commands:
  ptymark engine check
  ptymark run [OPTIONS] -- COMMAND [ARG...]
  ptymark shell [--source|--safe] [--private] -- COMMAND [ARG...]"
)]
struct Cli {
    /// Use an explicit user configuration file.
    #[arg(long, global = true, value_name = "PATH")]
    config: Option<PathBuf>,

    /// Select a named schema-v2 profile.
    #[arg(long, global = true, value_name = "NAME")]
    profile: Option<String>,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Preview a file or standard input through the pre-display pipeline.
    Preview(PreviewArgs),
    /// Filter the stdout of a non-interactive child process.
    Run(RunArgs),
    /// Run a child in a native PTY/ConPTY session.
    Shell(ShellArgs),
    /// Validate, inspect, or migrate user configuration.
    Config(ConfigArgs),
    /// Inspect configured renderer executables.
    Engine(EngineArgs),
    /// Produce a redacted supportability report.
    Doctor(DoctorArgs),
    /// Resolve or inspect installation state.
    Install(InstallArgs),
}

#[derive(Clone, Copy, Debug, Default, Args)]
struct RenderArgs {
    /// Detect complete blocks but display exact source.
    #[arg(long, conflicts_with = "safe")]
    source: bool,
    /// Bypass semantic detection and rendering.
    #[arg(long, conflicts_with = "source")]
    safe: bool,
    /// Disable process-local caches and persistence-capable diagnostics.
    #[arg(long)]
    private: bool,
    /// Fail rather than restoring source after renderer errors.
    #[arg(long)]
    strict: bool,
    /// Disable the in-memory artifact cache.
    #[arg(long)]
    no_cache: bool,
    /// Request color when the selected profile permits automatic color.
    #[arg(long)]
    color: bool,
    /// Override the renderer width hint for this invocation.
    #[arg(long, value_parser = clap::value_parser!(u16).range(1..))]
    columns: Option<u16>,
}

impl RenderArgs {
    fn pipeline(self) -> PipelineOptions {
        PipelineOptions {
            source: self.source,
            safe: self.safe,
            private: self.private,
            strict: self.strict,
            no_cache: self.no_cache,
            color: self.color,
            columns: self.columns,
            theme_fingerprint: 0,
        }
    }
}

#[derive(Debug, Args)]
struct PreviewArgs {
    #[command(flatten)]
    render: RenderArgs,
    /// Input file, or `-`/omitted for standard input.
    #[arg(value_name = "FILE", value_parser = OsStringValueParser::new())]
    input: Option<OsString>,
}

#[derive(Debug, Args)]
#[command(after_help = "The child stdout is filtered through a pipe; stdout is a pipe, not a PTY.")]
struct RunArgs {
    #[command(flatten)]
    render: RenderArgs,
    /// Child command and arguments. The `--` delimiter is required.
    #[arg(
        last = true,
        required = true,
        num_args = 1..,
        value_name = "COMMAND",
        value_parser = OsStringValueParser::new()
    )]
    command: Vec<OsString>,
}

#[derive(Debug, Args)]
struct ShellArgs {
    #[command(flatten)]
    render: RenderArgs,
    /// Allow intentional nested Ptymark sessions for development/debugging.
    #[arg(long)]
    allow_nested: bool,
    /// Child command and arguments. The `--` delimiter is required.
    #[arg(
        last = true,
        required = true,
        num_args = 1..,
        value_name = "COMMAND",
        value_parser = OsStringValueParser::new()
    )]
    command: Vec<OsString>,
}

#[derive(Debug, Args)]
struct ConfigArgs {
    #[command(subcommand)]
    action: ConfigAction,
}

#[derive(Debug, Subcommand)]
enum ConfigAction {
    /// Validate and resolve the selected profile without side effects.
    Check,
    /// Print normalized user-authored TOML without internal paths/limits.
    Show,
    /// Normalize schema v1 or v2 input to schema v2.
    Migrate {
        /// Atomically replace the selected configuration file.
        #[arg(long)]
        write: bool,
    },
}

#[derive(Debug, Args)]
struct EngineArgs {
    #[command(subcommand)]
    action: EngineAction,
}

#[derive(Debug, Subcommand)]
enum EngineAction {
    /// Resolve configured external engines and presenter.
    Check,
}

#[derive(Debug, Args)]
struct DoctorArgs {
    #[command(flatten)]
    render: RenderArgs,
    /// Emit `ptymark.doctor.v1` JSON.
    #[arg(long)]
    json: bool,
    /// Atomically write a redacted support report to a new file.
    #[arg(long, value_name = "PATH")]
    support_report: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct InstallArgs {
    #[command(subcommand)]
    action: InstallAction,
}

#[derive(Debug, Subcommand)]
enum InstallAction {
    /// Resolve user intent and installation-owned executable paths.
    Resolve(InstallResolveArgs),
    /// Inspect the installation ownership snapshot.
    Status(InstallStatusArgs),
}

#[derive(Debug, Args)]
struct InstallResolveArgs {
    /// Override the installation-state path.
    #[arg(long, value_name = "PATH")]
    state: Option<PathBuf>,
    /// keep | auto | preview | source | EXECUTABLE
    #[arg(long, default_value = "keep", value_parser = OsStringValueParser::new())]
    mermaid: OsString,
    /// keep | auto | preview | source | EXECUTABLE
    #[arg(long, default_value = "keep", value_parser = OsStringValueParser::new())]
    math: OsString,
    /// keep | auto | EXECUTABLE
    #[arg(long, default_value = "keep", value_parser = OsStringValueParser::new())]
    presenter: OsString,
    /// Start from the built-in schema-v2 user configuration.
    #[arg(long)]
    reset: bool,
    /// Print the user configuration and internal state plan without writes.
    #[arg(long)]
    dry_run: bool,
}

#[derive(Debug, Args)]
struct InstallStatusArgs {
    /// Override the installation-state path.
    #[arg(long, value_name = "PATH")]
    state: Option<PathBuf>,
}

pub fn main_entry() -> ! {
    if let Some(result) = crate::managed_launcher::run_if_managed_alias() {
        match result {
            Ok(code) => process::exit(code),
            Err(message) => {
                eprintln!("ptymark managed launcher: {message}");
                process::exit(2);
            }
        }
    }
    match run_from(env::args_os().skip(1).collect()) {
        Ok(code) => process::exit(code),
        Err(message) => {
            eprintln!("ptymark: {message}");
            process::exit(2);
        }
    }
}

pub fn run_from(arguments: Vec<OsString>) -> Result<i32, String> {
    let arguments = normalize_legacy_shell(arguments);
    validate_render_conflicts(&arguments)?;
    let argv = std::iter::once(OsString::from("ptymark")).chain(arguments);
    let cli = match Cli::try_parse_from(argv) {
        Ok(cli) => cli,
        Err(error) => {
            let code = error.exit_code();
            error
                .print()
                .map_err(|print_error| format!("cannot print CLI diagnostic: {print_error}"))?;
            return Ok(code);
        }
    };

    match cli.command {
        Command::Preview(arguments) => run_preview(arguments, cli.config, cli.profile.as_deref()),
        Command::Run(arguments) => crate::filtered_run::run(
            arguments.command,
            cli.config,
            cli.profile,
            arguments.render.pipeline(),
        ),
        Command::Shell(arguments) => crate::interactive::run(
            arguments.command,
            cli.config,
            cli.profile,
            arguments.render.pipeline(),
            arguments.allow_nested,
        ),
        Command::Config(arguments) => run_config(arguments, cli.config, cli.profile.as_deref()),
        Command::Engine(arguments) => run_engine(arguments, cli.config, cli.profile.as_deref()),
        Command::Doctor(arguments) => run_doctor(arguments, cli.config, cli.profile),
        Command::Install(arguments) => run_install(arguments, cli.config),
    }
}

fn validate_render_conflicts(arguments: &[OsString]) -> Result<(), String> {
    let mut source = false;
    let mut safe = false;
    for argument in arguments {
        match argument.to_str() {
            Some("--") => break,
            Some("--source") => source = true,
            Some("--safe") => safe = true,
            _ => {}
        }
    }
    if source && safe {
        return Err("`--source` and `--safe` cannot be combined".to_owned());
    }
    Ok(())
}

fn normalize_legacy_shell(mut arguments: Vec<OsString>) -> Vec<OsString> {
    if arguments.is_empty() {
        return arguments;
    }
    let mut index = 0_usize;
    while index < arguments.len() {
        match arguments[index].to_str() {
            Some("--config" | "--profile") => index = index.saturating_add(2),
            _ => break,
        }
    }
    let Some(token) = arguments.get(index).and_then(|value| value.to_str()) else {
        arguments.insert(index, OsString::from("shell"));
        return arguments;
    };
    const COMMANDS: &[&str] = &[
        "preview", "run", "shell", "config", "engine", "doctor", "install",
    ];
    if COMMANDS.contains(&token) || matches!(token, "-h" | "--help" | "-V" | "--version") {
        return arguments;
    }
    arguments.insert(index, OsString::from("shell"));
    arguments
}

fn run_preview(
    arguments: PreviewArgs,
    config_path: Option<PathBuf>,
    profile: Option<&str>,
) -> Result<i32, String> {
    let config =
        Config::load_profile(config_path.as_deref(), profile).map_err(|error| error.to_string())?;
    let mut pipeline = PipelineFactory::new(&config).build(arguments.render.pipeline());
    let mut input: Box<dyn Read> = match arguments.input {
        Some(path) if path != "-" => {
            let path = PathBuf::from(path);
            Box::new(
                File::open(&path)
                    .map_err(|error| format!("cannot open `{}`: {error}", path.display()))?,
            )
        }
        _ => Box::new(io::stdin()),
    };
    let stdout = io::stdout();
    let mut display = stdout.lock();

    PipelinePump::standard()
        .run(input.as_mut(), &mut display, &mut pipeline)
        .map_err(|error| format!("cannot process preview input: {error}"))?;
    Ok(0)
}

fn run_config(
    arguments: ConfigArgs,
    config_path: Option<PathBuf>,
    profile: Option<&str>,
) -> Result<i32, String> {
    match arguments.action {
        ConfigAction::Check => {
            let config = Config::load_profile(config_path.as_deref(), profile)
                .map_err(|error| error.to_string())?;
            println!(
                "configuration ok: schema={} profile={} renderer={:?} presentation={:?} mermaid={} math={}",
                config.schema_version,
                config.selected_profile,
                config.rendering.mode,
                config.rendering.presentation,
                config.engines.mermaid.backend.as_str(),
                config.engines.math.backend.as_str()
            );
            Ok(0)
        }
        ConfigAction::Show => {
            let config = Config::load_profile(config_path.as_deref(), profile)
                .map_err(|error| error.to_string())?;
            print!("{}", config.to_toml().map_err(|error| error.to_string())?);
            Ok(0)
        }
        ConfigAction::Migrate { write } => {
            let path = config_path
                .map(Ok)
                .unwrap_or_else(Config::user_config_path)
                .map_err(|error| error.to_string())?;
            let user = UserConfig::load_exact(&path).map_err(|error| error.to_string())?;
            let normalized = user.to_toml().map_err(|error| error.to_string())?;
            if write {
                atomic_replace_text(&path, normalized.as_bytes())?;
                println!(
                    "migrated\t{}\tschema={}",
                    path.display(),
                    user.schema_version
                );
            } else {
                print!("{normalized}");
            }
            Ok(0)
        }
    }
}

fn run_engine(
    arguments: EngineArgs,
    config_path: Option<PathBuf>,
    profile: Option<&str>,
) -> Result<i32, String> {
    match arguments.action {
        EngineAction::Check => {
            let config = Config::load_profile(config_path.as_deref(), profile)
                .map_err(|error| error.to_string())?;
            for check in
                check_configured_engines(&config.engines).map_err(|error| error.to_string())?
            {
                println!("{}", check.display_line());
            }
            Ok(0)
        }
    }
}

fn run_doctor(
    arguments: DoctorArgs,
    config_path: Option<PathBuf>,
    profile: Option<String>,
) -> Result<i32, String> {
    let report = DoctorReport::collect(DoctorRequest {
        config_path,
        profile,
        pipeline: arguments.render.pipeline(),
    });
    if let Some(path) = arguments.support_report {
        report.write_support_report(&path)?;
        if !arguments.json {
            println!("support report\t{}", path.display());
        }
    }
    if arguments.json {
        print!("{}", report.json());
    } else {
        print!("{}", report.human());
    }
    Ok(report.status.exit_code())
}

fn run_install(arguments: InstallArgs, config_path: Option<PathBuf>) -> Result<i32, String> {
    match arguments.action {
        InstallAction::Resolve(arguments) => run_install_resolve(arguments, config_path),
        InstallAction::Status(arguments) => run_install_status(arguments),
    }
}

fn run_install_resolve(
    arguments: InstallResolveArgs,
    config_path: Option<PathBuf>,
) -> Result<i32, String> {
    let config_path = config_path
        .map(Ok)
        .unwrap_or_else(Config::user_config_path)
        .map_err(|error| error.to_string())?;
    let state_path = arguments
        .state
        .map(Ok)
        .unwrap_or_else(default_install_state_path)
        .map_err(|error| error.to_string())?;
    let mut request = InstallRequest::new(config_path, state_path);
    request.mermaid = engine_preference(arguments.mermaid, "--mermaid")?;
    request.math = engine_preference(arguments.math, "--math")?;
    request.presenter = presenter_preference(arguments.presenter)?;
    request.reset = arguments.reset;

    let plan = Installer::new(PathProgramResolver)
        .plan(&request)
        .map_err(|error| error.to_string())?;
    if arguments.dry_run {
        println!("# user-authored ptymark configuration");
        print!(
            "{}",
            plan.user_config
                .to_toml()
                .map_err(|error| error.to_string())?
        );
        println!("# internal installation state");
        print!(
            "{}",
            plan.state.to_toml().map_err(|error| error.to_string())?
        );
    } else {
        plan.apply().map_err(|error| error.to_string())?;
        for line in plan.summary_lines() {
            println!("{line}");
        }
    }
    Ok(0)
}

fn run_install_status(arguments: InstallStatusArgs) -> Result<i32, String> {
    let state_path = arguments
        .state
        .map(Ok)
        .unwrap_or_else(default_install_state_path)
        .map_err(|error| error.to_string())?;
    let state = InstallState::load(&state_path).map_err(|error| error.to_string())?;
    println!("state\t{}", state_path.display());
    for line in state.status_lines(&PathProgramResolver) {
        println!("{line}");
    }
    Ok(0)
}

fn engine_preference(value: OsString, option: &str) -> Result<EnginePreference, String> {
    Ok(match value.to_str() {
        Some("keep") => EnginePreference::Keep,
        Some("auto") => EnginePreference::Auto,
        Some("preview") => EnginePreference::Preview,
        Some("source") => EnginePreference::Source,
        Some("") => return Err(format!("`{option}` cannot be empty")),
        _ => EnginePreference::External(PathBuf::from(value)),
    })
}

fn presenter_preference(value: OsString) -> Result<PresenterPreference, String> {
    Ok(match value.to_str() {
        Some("keep") => PresenterPreference::Keep,
        Some("auto") => PresenterPreference::Auto,
        Some("preview" | "source") => {
            return Err("`--presenter` accepts keep, auto, or an executable path".to_owned());
        }
        Some("") => return Err("`--presenter` cannot be empty".to_owned()),
        _ => PresenterPreference::Program(PathBuf::from(value)),
    })
}

fn atomic_replace_text(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    if !parent.is_dir() {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "cannot create configuration directory `{}`: {error}",
                parent.display()
            )
        })?;
    }
    let mut temporary = tempfile::Builder::new()
        .prefix(".ptymark-config-")
        .tempfile_in(parent)
        .map_err(|error| format!("cannot create migration temporary file: {error}"))?;
    temporary
        .write_all(bytes)
        .and_then(|()| temporary.as_file().sync_all())
        .map_err(|error| format!("cannot stage migrated configuration: {error}"))?;
    temporary.persist(path).map_err(|error| {
        format!(
            "cannot replace configuration `{}`: {}",
            path.display(),
            error.error
        )
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::normalize_legacy_shell;
    use std::ffi::OsString;

    #[test]
    fn alpha3_interactive_form_is_normalized_to_shell() {
        let input = vec![
            OsString::from("--source"),
            OsString::from("--"),
            OsString::from("bash"),
        ];
        let normalized = normalize_legacy_shell(input);
        assert_eq!(normalized[0], "shell");
        assert_eq!(normalized[1], "--source");
    }

    #[test]
    fn explicit_subcommands_are_not_rewritten() {
        let input = vec![OsString::from("preview")];
        assert_eq!(normalize_legacy_shell(input.clone()), input);
    }

    #[test]
    fn leading_global_config_keeps_legacy_shell_position() {
        let input = vec![
            OsString::from("--config"),
            OsString::from("config.toml"),
            OsString::from("--"),
            OsString::from("bash"),
        ];
        let normalized = normalize_legacy_shell(input);
        assert_eq!(normalized[2], "shell");
    }
}
